using System.Text.Json;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

QuestPDF.Settings.License = LicenseType.Community;

var serviceToken = Environment.GetEnvironmentVariable("PDF_SERVICE_TOKEN");

app.MapGet("/health", () => Results.Ok(new { status = "ok", engine = "QuestPDF" }));

app.MapPost("/v1/documents/render", async (HttpRequest request) =>
{
    if (!string.IsNullOrWhiteSpace(serviceToken))
    {
        var auth = request.Headers.Authorization.ToString();
        var expected = $"Bearer {serviceToken}";
        if (!string.Equals(auth, expected, StringComparison.Ordinal))
            return Results.Unauthorized();
    }

    RenderRequest? model;
    try
    {
        model = await JsonSerializer.DeserializeAsync<RenderRequest>(request.Body, new JsonSerializerOptions
        {
            PropertyNameCaseInsensitive = true
        });
    }
    catch (Exception ex)
    {
        return Results.BadRequest(new { error = "Invalid JSON payload", detail = ex.Message });
    }

    if (model is null || string.IsNullOrWhiteSpace(model.Title))
        return Results.BadRequest(new { error = "Missing required fields" });

    var pdf = Document.Create(container =>
    {
        container.Page(page =>
        {
            page.Size(PageSizes.A4);
            page.Margin(24);
            page.DefaultTextStyle(x => x.FontSize(11));

            page.Header().Column(col =>
            {
                col.Spacing(4);
                col.Item().Text(model.Title).FontSize(20).SemiBold();
                col.Item().Text($"Reference: {model.Reference ?? "-"}");
                col.Item().Text($"Issued At: {model.IssuedAtIso ?? DateTime.UtcNow.ToString("O")}");
            });

            page.Content().PaddingVertical(12).Column(col =>
            {
                col.Spacing(8);
                col.Item().Text($"From: {model.Parties?.From ?? "-"}");
                col.Item().Text($"To: {model.Parties?.To ?? "-"}");
                col.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);

                col.Item().Table(table =>
                {
                    table.ColumnsDefinition(columns =>
                    {
                        columns.RelativeColumn();
                        columns.ConstantColumn(60);
                        columns.ConstantColumn(100);
                        columns.ConstantColumn(100);
                    });

                    table.Header(header =>
                    {
                        header.Cell().Text("Item").SemiBold();
                        header.Cell().AlignRight().Text("Qty").SemiBold();
                        header.Cell().AlignRight().Text("Unit").SemiBold();
                        header.Cell().AlignRight().Text("Total").SemiBold();
                    });

                    foreach (var line in model.LineItems ?? Enumerable.Empty<LineItem>())
                    {
                        table.Cell().Text(line.Label ?? "-");
                        table.Cell().AlignRight().Text(line.Quantity.ToString("0.##"));
                        table.Cell().AlignRight().Text(FormatMoney(model.Currency, line.UnitAmount));
                        table.Cell().AlignRight().Text(FormatMoney(model.Currency, line.TotalAmount));
                    }
                });

                col.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
                col.Item().AlignRight().Text($"Gross: {FormatMoney(model.Currency, model.Totals?.Gross ?? 0)}");

                if ((model.Totals?.Fee ?? 0) > 0)
                    col.Item().AlignRight().Text($"Fee: {FormatMoney(model.Currency, model.Totals?.Fee ?? 0)}");

                if ((model.Totals?.Net ?? 0) > 0)
                    col.Item().AlignRight().Text($"Net: {FormatMoney(model.Currency, model.Totals?.Net ?? 0)}").SemiBold();

                if (!string.IsNullOrWhiteSpace(model.Notes))
                {
                    col.Item().PaddingTop(12).Text("Notes").SemiBold();
                    col.Item().Text(model.Notes);
                }
            });

            page.Footer().AlignCenter().Text($"Generated by IbaHub PDF Service ({model.Template ?? "document"})");
        });
    }).GeneratePdf();

    return Results.File(pdf, "application/pdf");
});

app.Run();

static string FormatMoney(string? currency, decimal value)
{
    var code = string.IsNullOrWhiteSpace(currency) ? "NGN" : currency.ToUpperInvariant();
    return $"{code} {value:N2}";
}

public sealed class RenderRequest
{
    public string? Template { get; set; }
    public string? Title { get; set; }
    public string? Reference { get; set; }
    public string? IssuedAtIso { get; set; }
    public string? Currency { get; set; }
    public PartyBlock? Parties { get; set; }
    public TotalBlock? Totals { get; set; }
    public List<LineItem>? LineItems { get; set; }
    public string? Notes { get; set; }
}

public sealed class PartyBlock
{
    public string? From { get; set; }
    public string? To { get; set; }
}

public sealed class TotalBlock
{
    public decimal Gross { get; set; }
    public decimal Fee { get; set; }
    public decimal Net { get; set; }
}

public sealed class LineItem
{
    public string? Label { get; set; }
    public decimal Quantity { get; set; }
    public decimal UnitAmount { get; set; }
    public decimal TotalAmount { get; set; }
}
